In [1]:
import numpy as np

In [2]:
# обратная матрица - все ок
A1=np.array([[1,2,3],[4,5,6],[7,8,10]])
print('A1:\n',A1)

A1:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [3]:
print('rk(A3):\n',np.linalg.matrix_rank(A1))

rk(A3):
 3


In [4]:
# обратная матрица - все ок
A1_inv=np.linalg.inv(A1)
print('A1 inversed:\n',A1_inv)


A1 inversed:
 [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [5]:
# обратная матрица - все ок
print('A1 @ A1 inversed=E check:\n',A1@A1_inv,1)
print(np.round(A1@A1_inv,1))
print('check OK')

A1 @ A1 inversed=E check:
 [[ 1.00000000e+00  8.88178420e-16 -4.44089210e-16]
 [ 0.00000000e+00  1.00000000e+00 -1.77635684e-15]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]] 1
[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]
check OK


In [6]:
# обратная матрица - вырожденный случай
A2=np.array([[1,2,3],[4,5,6],[1,2,3]])
print('A2:\n',A2)

A2:
 [[1 2 3]
 [4 5 6]
 [1 2 3]]


In [7]:
# обратная матрица - вырожденный случай
print('rk(A3):\n',np.linalg.matrix_rank(A2))

rk(A3):
 2


In [8]:
# обратная матрица - вырожденный случай
np.linalg.inv(A2)

LinAlgError: Singular matrix

In [ ]:
# обратная матрица - magic
A3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A3:\n',A3)

In [ ]:
# обратная матрица - magic
print('rk(A3):\n',np.linalg.matrix_rank(A3))

In [ ]:
# обратная матрица - magic
print('A3 inversed:\n',np.linalg.inv(A3))

In [ ]:
# обратная матрица - magic
print('A3 @ A3 inversed = E check:\n',A3@np.linalg.inv(A3))
print('check failed')

In [ ]:
print('det(A1)):\n',np.linalg.det(A1))

In [ ]:
print('det(A2)):\n',np.linalg.det(A2))

In [ ]:
print('det(A3)):\n',np.linalg.det(A3))

In [ ]:
# обратная матрица - неустойчивость
A4=np.array([[1,2,3],[4,5,6],[1,2,3.00005]])
print('A4:\n',A4)
print('rk(A4):\n',np.linalg.matrix_rank(A4))
print('det(A4):\n',np.linalg.det(A4))
print('A4 inverse:\n',np.linalg.inv(A4))

In [ ]:
# обратная матрица - неустойчивость вблизи нулевого определителя
A5=np.array([[1,2,3],[4,5,6],[1,2,3.00000005]])
print('A5:\n',A5)
print('rk(A5):\n',np.linalg.matrix_rank(A5))
print('det(A5):\n',np.linalg.det(A5))
print('A5 inverse:\n',np.linalg.inv(A5))

In [ ]:
# обратимость матрицы Грама линейно независимой системы векторов
v1=np.array([1,2,1])
v2=np.array([1,1,1])
A=np.array([v1,v2]).T
print('A:\n',A)
print('Матрица Грама:\n',A.T@A)

In [ ]:
print('Ранг матрицы Грама:\n',np.linalg.matrix_rank(A.T@A))

In [ ]:
print('Определитель матрицы Грама:\n',np.linalg.det(A.T@A))

In [ ]:
print('Обратная к матрице Грама:\n',np.linalg.inv(A.T@A))