### Векторы и действия над ними

In [3]:
# Вызываем библиотеку numpy, т. к. именно в ней удобнее всего работать с векторами.
import numpy as np

# Задаём вектор  как одномерный массив numpy с помощью функции np.array.
s = np.array([33, 64, 50, 45])
print(s)

# Находим третью координату. Помним, что в Python массивы нумеруются с нуля, а не с единицы, 
# поэтому для третьей квартиры нужен элемент массива с номером 2.
print(s[2])

# Находим размерность вектора. За размерность отвечает функция len().
print(len(s))

[33 64 50 45]
50
4


### Сложение и вычитание векторов

In [4]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print(a + b)
print(a - b)

[15 23 14  8]
[ 5 -7 -4 -6]


### Умножение векторов

In [5]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
print(c)

[24.   9.  13.6]
