### Векторы и действия над ними

In [2]:
# Вызываем библиотеку numpy, т. к. именно в ней удобнее всего работать с векторами.
import numpy as np

# Задаём вектор  как одномерный массив numpy с помощью функции np.array.
s = np.array([33, 64, 50, 45])
print(s)

# Находим третью координату. Помним, что в Python массивы нумеруются с нуля, а не с единицы, 
# поэтому для третьей квартиры нужен элемент массива с номером 2.
print(s[2])

# Находим размерность вектора. За размерность отвечает функция len().
print(len(s))

[33 64 50 45]
50
4


### Сложение и вычитание векторов

In [3]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print(a + b)
print(a - b)

[15 23 14  8]
[ 5 -7 -4 -6]


### Умножение векторов

In [4]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
print(c)

[24.   9.  13.6]


###  Линейная комбинация векторов

In [5]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u

array([1800, 3000, 2700])

    Скалярное произведение. Результат — число. 
    Векторное произведение. Результат — вектор.
    Смешанное произведение. Результат — число. 
    Тензорное произведение. Результат — матрица.

In [6]:
# Скалярное произведение
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)

102.0

### Практика
В Hut_Paradise_DF представлен фрагмент базы данных агентства «Рай в Шалаше». По строкам расположены квартиры, по столбцам — параметры: арендная плата, общая площадь, количество комнат, этаж, количество показов на две недели и жилая площадь:

In [7]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

### Задание 3.3
Найдите вектор параметров квартиры номер 5 (нумерация квартир — с 1). Для преобразования DataFrame в массив numpy можно воспользоваться атрибутом values:

In [8]:
Hut_Paradise_values = Hut_Paradise_DF.values
Hut_Paradise_values[4]

array([40, 33,  1,  6, 20, 16])

### Задание 3.4
Найдите вектор этажей всех квартир. Выберите координаты полученного вектора:

In [9]:
Hut_Paradise_values[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

###  Задание 3.5
Вычислите вектор нежилой площади. Выберите координаты полученного вектора:

In [10]:
Hut_Paradise_values[:,1] - Hut_Paradise_values[:,5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

###  Задание 3.6
Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

Найдите продолжительность просмотров в минутах во всех квартирах за две недели.

In [11]:
# вектор времени осмотра
t = np.array([10,20,30,15,5,40,20,8,20])
np.dot(Hut_Paradise_values[:,4], t)

1348

### Задание 3.7
Дано три вектора:
- u=np.array([3,0,1,1,1])
- v=np.array([0,1,0,2,-2])
- w=np.array([1,-4,-1,0,-2])

Составьте линейную комбинацию векторов и с коэффициентами 2 и -3. Выберите координаты полученного вектора:

In [12]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

omega1 = 2
omega2 = -3
omega3 = 0
omega1*u + omega2*v + omega3*w

array([ 6, -3,  2, -4,  8])

### Матрицы и базовые действия с ними

In [13]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [14]:
A.shape
## (4, 3)
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])
## a_23= 1 a_32= 3 a_33= 1

a_23= 1 a_32= 3 a_33= 1


### Базовые действия над матрицами

In [15]:
# Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы numpy:

import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

###  Задание 5.1
Составьте матрицу доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.

В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.

In [21]:
family_income = np.array([
    Husband_Income, 
    Wife_Income,
    Mother_In_Law_Income
])
family_income.T

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

###  Задание 5.2
Составьте матрицу расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.

В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.

In [22]:
family_Consumption = np.array([
    Husband_Consumption, 
    Wife_Consumption,
    Mother_In_Law_Consumption
])
family_Consumption.T

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

###  Задание 5.3
Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

Используйте полученную ранее матрицу , где доходы расположены по столбцам.

In [26]:
family_income.T*(1-0.13)

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

###  Задание 5.4
Вычислите матрицу , которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами после вычета налога и расходами).

In [27]:
family_income.T*(1-0.13)-family_Consumption.T

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])