### Векторы и действия над ними

In [58]:
# Вызываем библиотеку numpy, т. к. именно в ней удобнее всего работать с векторами.
import numpy as np

# Задаём вектор  как одномерный массив numpy с помощью функции np.array.
s = np.array([33, 64, 50, 45])
print(s)

# Находим третью координату. Помним, что в Python массивы нумеруются с нуля, а не с единицы, 
# поэтому для третьей квартиры нужен элемент массива с номером 2.
print(s[2])

# Находим размерность вектора. За размерность отвечает функция len().
print(len(s))

[33 64 50 45]
50
4


### Сложение и вычитание векторов

In [59]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print(a + b)
print(a - b)

[15 23 14  8]
[ 5 -7 -4 -6]


### Умножение векторов

In [60]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
print(c)

[24.   9.  13.6]


###  Линейная комбинация векторов

In [61]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u

array([1800, 3000, 2700])

    Скалярное произведение. Результат — число. 
    Векторное произведение. Результат — вектор.
    Смешанное произведение. Результат — число. 
    Тензорное произведение. Результат — матрица.

In [62]:
# Скалярное произведение
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)

102.0

### Практика
В Hut_Paradise_DF представлен фрагмент базы данных агентства «Рай в Шалаше». По строкам расположены квартиры, по столбцам — параметры: арендная плата, общая площадь, количество комнат, этаж, количество показов на две недели и жилая площадь:

In [63]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

### Задание 3.3
Найдите вектор параметров квартиры номер 5 (нумерация квартир — с 1). Для преобразования DataFrame в массив numpy можно воспользоваться атрибутом values:

In [64]:
Hut_Paradise_values = Hut_Paradise_DF.values
Hut_Paradise_values[4]

array([40, 33,  1,  6, 20, 16])

### Задание 3.4
Найдите вектор этажей всех квартир. Выберите координаты полученного вектора:

In [65]:
Hut_Paradise_values[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

###  Задание 3.5
Вычислите вектор нежилой площади. Выберите координаты полученного вектора:

In [66]:
Hut_Paradise_values[:,1] - Hut_Paradise_values[:,5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

###  Задание 3.6
Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

Найдите продолжительность просмотров в минутах во всех квартирах за две недели.

In [67]:
# вектор времени осмотра
t = np.array([10,20,30,15,5,40,20,8,20])
np.dot(Hut_Paradise_values[:,4], t)

1348

### Задание 3.7
Дано три вектора:
- u=np.array([3,0,1,1,1])
- v=np.array([0,1,0,2,-2])
- w=np.array([1,-4,-1,0,-2])

Составьте линейную комбинацию векторов и с коэффициентами 2 и -3. Выберите координаты полученного вектора:

In [68]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

omega1 = 2
omega2 = -3
omega3 = 0
omega1*u + omega2*v + omega3*w

array([ 6, -3,  2, -4,  8])

### Матрицы и базовые действия с ними

In [69]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [70]:
A.shape
## (4, 3)
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])
## a_23= 1 a_32= 3 a_33= 1

a_23= 1 a_32= 3 a_33= 1


### Базовые действия над матрицами

In [71]:
# Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы numpy:

import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

###  Задание 5.1
Составьте матрицу доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.

В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.

In [72]:
family_income = np.array([
    Husband_Income, 
    Wife_Income,
    Mother_In_Law_Income
])
family_income.T

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

###  Задание 5.2
Составьте матрицу расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.

В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.

In [73]:
family_Consumption = np.array([
    Husband_Consumption, 
    Wife_Consumption,
    Mother_In_Law_Consumption
])
family_Consumption.T

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

###  Задание 5.3
Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

Используйте полученную ранее матрицу , где доходы расположены по столбцам.

In [74]:
family_income.T*(1-0.13)

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

###  Задание 5.4
Вычислите матрицу , которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами после вычета налога и расходами).

In [75]:
family_income.T*(1-0.13)-family_Consumption.T

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

### Умножение матриц

In [76]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [77]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [78]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

### Резюмируем общие правила умножения матриц:

- Число столбцов левой матрицы должно совпадать с числом строк правой матрицы
- Строки левой матрицы скалярно умножаются на столбцы правой матрицы
- Матричное умножение не перестановочно в общем случае (A*B не равно B*A)

### Важные выводы:

- Нулевая и единичная матрицы играют роль нуля и единицы в матричном умножении.
- Умножение на шаровую матрицу — то же самое, что умножение на скаляр.
- Умножение на диагональную матрицу даёт растяжение каждого столбца или строки.
- Диагональные матрицы коммутативны между собой.

###  Задание 7.1
Даны матрица \(A\) и вектор \(х\):

        A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
        x = np.array([1,2,3,4,5])

Найдите произведение матрицы \(A\) и вектора \(х\) в том порядке, в котором их можно умножить.

In [79]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
np.dot(A, x)

array([26, 30])

###  Задание 7.2
Даны две матрицы:

        A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
        B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

Найдите произведение матриц \(A\) и \(B\) в том порядке, в котором их можно умножить.

In [80]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
np.dot(B, A)

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

###  Задание 7.3
Дана система векторов:

        x = np.array([1,2,1,0,4])
        y = np.array([2,1,-1,1,0])
        z = np.array([-1,1,-1,0,0])

Составьте матрицу \(A\), расположив векторы \(x\), \(y\), \(z\) в строках. Найдите матрицу Грама \(G\) системы векторов \(x\), \(y\), \(z\).

Чему равна полученная матрица Грама \(G\)?

In [81]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
A = np.array([
    x, 
    y,
    z
])
A.T@A

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

### Задания 7.4 и 7.5

В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 

Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.

        В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.
        В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят салону определённую комиссию.
Вектор комиссий: com = np.array([0.2, 0.2, 0.3, 0.1, 0.1]).
Выберите координаты вектора прибыли салона.

Найдите вектор прибыли стилистов.
Выберите координаты полученного вектора.

In [82]:
# условия заданий
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [83]:
np.dot(Count_DF*Price_DF,com)

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [84]:
np.dot(Count_DF*Price_DF,(1-com))

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

### Обратная матрица

In [85]:
A = np.matrix('1,2,3; 4,5,6; 7, 8, 10')
A

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 10]])

In [86]:
np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

###  Задание 8.2
Вычислите обратную матрицу

In [87]:
A = np.matrix('1,2; 2,5')
np.linalg.inv(A)

matrix([[ 5., -2.],
        [-2.,  1.]])

### Определитель матрицы
У определителя есть множество полезных свойств. Вот некоторые из них:
- Определитель единичной матрицы предсказуемо равен единице
- Для диагональной матрицы определитель равен произведению диагональных элементов
- При умножении матрицу на константу  определитель увеличивается в раз, где  — порядок матрицы
- При транспонировании определитель матрицы не изменяется
- Определитель произведения матриц и равен произведению определителей этих матриц и не зависит от порядка умножения

Матрица называется вырожденной, если её определитель равен 0

In [88]:
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
print(np.linalg.det(A))
# -3.0000000000009

-2.9999999999999982


### Задание 8.6 
Найдите определитель матриц.

In [92]:
A = np.matrix ("1, 2; 1, 1")
B = np.matrix ("5, -2; -1, 4")
print(np.linalg.det(A), np.linalg.det(B), np.linalg.det(A+B))

-1.0 17.999999999999996 29.99999999999999


### Задание 8.7
Найдите определитель матриц.

In [94]:
A = np.matrix ("2, 0, 0; 0, 1, 0; 0, 0, 4")
print(np.linalg.det(A), np.linalg.det(np.linalg.inv(A)))

7.999999999999998 0.12500000000000003


### СЛАУ
Совокупность уравнений первой степени, в которых каждая переменная и коэффициенты в ней являются вещественными числами, называется системой линейных алгебраических уравнений (СЛАУ).

СЛАУ называется однородной, если все свободные члены системы равны 0.

СЛАУ называется неоднородной, если хотя бы один из свободных членов системы отличен от 0.

Решением СЛАУ называется такой набор значений неизвестных переменных при котором каждое уравнение системы превращается в равенство.

СЛАУ называется определённой, если она имеет только одно решение, и неопределённой, если возможно больше одного решения.

### Ранг матрицы
Ранг матрицы — это количество линейно независимых столбцов. Обозначение: или .

Ранг системы векторов — это размерность этой системы.

In [96]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))

2


Мы видим, что ранг системы равен 2, а векторов три — значит система является линейно зависимой.

In [97]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,10,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))

3


В данном примере ранг равен 3 — значит векторы линейно независимы и в базис войдут все три вектора.

###  Задание 10.1
Дана матрица :

A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

Найдите матрицу, обратную матрице .

In [98]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

### Задание 10.2
Найдите ранг системы векторов. Для этого создайте матрицу системы векторов. Векторы в матрице расположите в столбцы.

In [99]:
# условия
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [100]:
A = np.array([v1, v2, v3, v4]).T
print(np.linalg.matrix_rank(A))

4


###  Задание 10.4
Найдите матрицу Грама системы векторов. В качестве ответа запишите элемент из четвёртого столбца первой строки.

In [101]:
A.T@A

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

###  Задание 10.5
Найдите определитель матрицы Грама системы. Ответ округлите до целого числа.

In [104]:
np.linalg.det(A.T@A)

3716647.9999999995

###  Задание 10.7
Найдите обратную матрицу к матрице Грама системы. В качестве ответа запишите элемент из первого столбца третьей строки, округлив его до трёх знаков после точки-разделителя.

In [105]:
np.linalg.inv(A.T@A)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])